version: "3.8"
services:

  # container to run integration tests
  integration-tests:
    depends_on:
      database:
        condition: service_healthy
      engine:
        condition: service_healthy
      int-node-0-test:
        condition: service_healthy
    env_file:
      - environments/int-database.env
      - environments/int-integration-tester.env
    environment:
      - TEST_FILTER
    volumes:
      - logs-int:/logs/
    build:
      context: .
      dockerfile: ConsensusChessIntegrationTests/Dockerfile
    command: "--filter ${TEST_FILTER}"

volumes:
  logs-int:

