version: "3.8"
services:

  # additional configuration for the database
  database:
    env_file:
      - environments/db-prod.env
    volumes:
      - db-data-prod:/var/lib/postgresql/data/

  # additional configuration for the database
  engine:
    env_file:
      - environments/db-prod.env
      - environments/engine-prod.env

  node-prod-00:
    depends_on:
      database:
        condition: service_healthy
      engine:
        condition: service_healthy
    healthcheck:
      test: bash -c "[ -f /tmp/health.ready ]"
      interval: 5s
      timeout: 10s
      retries: 12
    env_file:
      - environments/db-prod.env
      - environments/node-prod-00.env
    build:
      context: .
      dockerfile: ConsensusChessNode/Dockerfile
    restart: unless-stopped

volumes:
  db-data-prod:
