version: "3.8"
services:

  # container to run integration tests
  integration-tests:
    depends_on:
      database:
        condition: service_healthy
      engine:
        condition: service_healthy
      node-int-00:
        condition: service_healthy
    env_file:
      - environments/db-int.env
      - environments/test-agent-int.env
    environment:
      - TEST_FILTER
    volumes:
      - logs-int:/logs/
    build:
      context: .
      dockerfile: ConsensusChessIntegrationTests/Dockerfile
    command: "--filter ${TEST_FILTER}"

volumes:
  logs-int:

