version: "3.8"
services:
  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file: environments/database.env
    volumes:
      - db-data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "pg_isready", "-U","${POSTGRES_USER}", "-d","${POSTGRES_DB}" ]
      interval: 5s
      timeout: 10s
      retries: 12
    restart: unless-stopped

  engine:
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: bash -c "[ -f /tmp/health.ready ]"
      interval: 5s
      timeout: 10s
      retries: 12
    env_file:
      - environments/engine.env
      - environments/database.env
    build:
      context: .
      dockerfile: ConsensusChessEngine/Dockerfile
    restart: unless-stopped

  node-0-test:
    depends_on:
      database:
        condition: service_healthy
      engine:
        condition: service_healthy
    healthcheck:
      test: bash -c "[ -f /tmp/health.ready ]"
      interval: 5s
      timeout: 10s
      retries: 12
    env_file:
      - environments/node-0-test.env
      - environments/database.env
    build:
      context: .
      dockerfile: ConsensusChessNode/Dockerfile
    restart: unless-stopped

volumes:
  db-data:
