version: "3.8"

# basic services are partially defined here: database and engine
# environment variables are provided for these in the int and prod compose yaml
services:
  database:
    image: 'postgres:latest'
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: "-p ${DB_PORT}"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U","${POSTGRES_USER}", "-d","${POSTGRES_DB}","-p","${DB_PORT}" ]
      interval: 5s
      timeout: 10s
      retries: 12
    restart: unless-stopped

  engine:
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: bash -c "[ -f /tmp/health.ready ]"
      interval: 5s
      timeout: 10s
      retries: 12
    build:
      context: .
      dockerfile: ConsensusChessEngine/Dockerfile
    restart: unless-stopped
