version: "3.8"
services:
  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file: environments/database.env
    volumes:
      - db-data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "pg_isready", "-U","${POSTGRES_USER}", "-d","${POSTGRES_DB}" ]
      interval: 2s
      timeout: 2s
      retries: 5

  engine:
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - environments/engine.env
      - environments/database.env
    build:
      context: .
      dockerfile: ConsensusChessEngine/Dockerfile

#  node-basic:
#    depends_on:
#      database:
#        condition: service_healthy
#    env_file:
#      - environments/node-basic.env
#      - environments/database.env
#    build:
#      context: .
#      dockerfile: ConsensusChessNode/Dockerfile

volumes:
  db-data:
